# Generated by Django 5.2.10 on 2026-02-03 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transactions_count', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('low_stock_items', models.IntegerField(default=0)),
                ('out_of_stock_items', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('insights', models.JSONField(default=dict)),
                ('recommendations', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('business', 'date')},
            },
        ),
    ]
