# Generated by Django 5.2.10 on 2026-02-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
